### ISSUE TITLE
Filter Not Applied When Using 'Refresh Charts' Button on Dashboard

### ISSUE THREAD

**Issue by alb3rtod** [chartbrew/chartbrew#259]
Hi @razvanilin 

I'm encountering an issue where the filter is not applied when using the 'Refresh Charts' button on the Dashboard. To apply the filter, I need to refresh each chart individually using the 'Refresh Chart' option in the three dots menu of each chart.

**Steps to Reproduce:**

1. Apply a filter to the dashboard.
2. Click the 'Refresh Charts' button on the Dashboard.
![{FDCA3474-6725-425B-AE2A-9A83056B07A0}](https://github.com/user-attachments/assets/b898bd7b-a813-4eb8-9809-bdca133e401b)

3. Observe that the filter is not applied to the charts.
![{57F7A822-49FE-45BF-A6AD-C11F544B2706}](https://github.com/user-attachments/assets/3d11b58e-40a3-46e9-98db-2a14bb649746)

4. Manually refresh a chart using the 'Refresh Chart' option in the three dots menu.
![{3BA0ABA2-40B9-4070-9A0E-E868F96674A2}](https://github.com/user-attachments/assets/499d056e-9846-4db2-9765-237eaa2276d7)

5. Notice that the filter is correctly applied to the individually refreshed chart.
![{F432BB60-24C3-4E15-8C79-4C42392EE980}](https://github.com/user-attachments/assets/f6e1647d-37ed-4806-91b3-e9d341ac8471)

**Expected Behavior:**
The filter should be applied to all charts when using the 'Refresh Charts' button on the Dashboard.

**Actual Behavior:**
The filter is only applied when refreshing each chart individually.

**Additional Information:**
Version: 3.9.0 (docker container)
DB: MySQL
PM2 Implemented

**Comment by alb3rtod** [comment]
A Refresh Filter button in the Dashboard would be great!

**Comment by razvanilin** [comment]
Hi @alb3rtod are you using the `latest` tag on Docker by any chance? This was an issue that was fixed in the latest fixes, but I did not create a new version yet

**Comment by alb3rtod** [comment]
Hi @razvanilin I cloned the repository on Wednesday and noticed that the most recent commit is the last one available (06581e53319ddeff12a298eb2c0b46ece4e46b79).

**Comment by alb3rtod** [comment]
Hi @razvanilin 

I have cloned the v3.10.0 repository, but the issue persists.
